parameters:
#    fi_personale.example.class: Fi\PersonaleBundle\Example

services:
#    fi_personale.example:
#        class: %fi_personale.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
