fi_spese_android:
    resource: "@FiSpeseBundle/Resources/config/routing/android.yml"
    prefix:   /android

fi_spese_famiglia:
    resource: "@FiSpeseBundle/Resources/config/routing/famiglia.yml"
    prefix:   /famiglia

fi_spese_reports:
    resource: "@FiSpeseBundle/Resources/config/routing/reports.yml"
    prefix:   /reports

fi_spese_movimento:
    resource: "@FiSpeseBundle/Resources/config/routing/movimento.yml"
    prefix:   /movimento

fi_spese_utente:
    resource: "@FiSpeseBundle/Resources/config/routing/utente.yml"
    prefix:   /utente

fi_spese_tipomovimento:
    resource: "@FiSpeseBundle/Resources/config/routing/tipomovimento.yml"
    prefix:   /tipomovimento

fi_spese_tipologia:
    resource: "@FiSpeseBundle/Resources/config/routing/tipologia.yml"
    prefix:   /tipologia

fi_spese_categoria:
    resource: "@FiSpeseBundle/Resources/config/routing/categoria.yml"
    prefix:   /categoria

FiSpeseBundle_android: 
  resource: "@FiSpeseBundle/Resources/config/routing/android.yml"
  prefix: /Android

FiSpeseBundle_categoria: 
  resource: "@FiSpeseBundle/Resources/config/routing/categoria.yml"
  prefix: /Categoria

FiSpeseBundle_tipologia: 
  resource: "@FiSpeseBundle/Resources/config/routing/tipologia.yml"
  prefix: /Tipologia

FiSpeseBundle_tipomovimento: 
  resource: "@FiSpeseBundle/Resources/config/routing/tipomovimento.yml"
  prefix: /Tipomovimento

FiSpeseBundle_utente: 
  resource: "@FiSpeseBundle/Resources/config/routing/utente.yml"
  prefix: /Utente

FiSpeseBundle_movimento: 
  resource: "@FiSpeseBundle/Resources/config/routing/movimento.yml"
  prefix: /Movimento

FiSpeseBundle_famiglia: 
  resource: "@FiSpeseBundle/Resources/config/routing/famiglia.yml"
  prefix: /Famiglia
