Fi\CoreBundle\Entity\menuApplicazione:
    type: entity
    table: menu_applicazione
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        nome:
            type: string
            length: 255
            nullable: true
        percorso:
            type: string
            length: 640
            nullable: true
        padre:
            type: integer
            nullable: true
        ordine:
            type: integer
            nullable: true
        attivo:
            type: boolean
            nullable: true
        target:
            type: string
            length: 255
            nullable: true
        tag:
            type: string
            length: 45
            nullable: true
        notifiche:
            type: boolean
            nullable: true
        autorizzazionerichiesta:
            type: boolean
            nullable: true
        percorsonotifiche:
            type: string
            length: 640
            nullable: true