parameters:
#    fi_network.example.class: Fi\NetworkBundle\Example

services:
#    fi_network.example:
#        class: %fi_network.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
