ffsecondaria:
    pattern:  /
    defaults: { _controller: "FiCoreBundle:ffsecondaria:index" }

ffsecondaria_new:
    pattern:  /new
    defaults: { _controller: "FiCoreBundle:ffsecondaria:new" }

ffsecondaria_create:
    pattern:  /create
    defaults: { _controller: "FiCoreBundle:ffsecondaria:create" }
    requirements: { _method: post }

ffsecondaria_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "FiCoreBundle:ffsecondaria:edit" }

ffsecondaria_update:
    pattern:  /{id}/update
    defaults: { _controller: "FiCoreBundle:ffsecondaria:update" }
    requirements: { _method: post|put }

ffprincipale_aggiorna:
    pattern:  /aggiorna
    defaults: { _controller: "FiCoreBundle:ffsecondaria:aggiorna" }
    requirements: { _method: post|put }

ffsecondaria_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "FiCoreBundle:ffsecondaria:delete" }
    requirements: { _method: post|delete }

ffsecondaria_deletemultiple:
    pattern:  /delete
    defaults: { _controller: "FiCoreBundle:ffsecondaria:delete" }
    requirements: { _method: post|delete }

ffsecondaria_griglia:
    pattern:  /griglia
    defaults: { _controller: "FiCoreBundle:ffsecondaria:griglia" }
    requirements: { _method: get }
