menuApplicazione_container:
    pattern:  /
    defaults: { _controller: "FiCoreBundle:menuApplicazione:index" }

menuApplicazione_new:
    pattern:  /new
    defaults: { _controller: "FiCoreBundle:menuApplicazione:new" }

menuApplicazione_create:
    pattern:  /create
    defaults: { _controller: "FiCoreBundle:menuApplicazione:create" }
    requirements: { _method: post }

menuApplicazione_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "FiCoreBundle:menuApplicazione:edit" }

menuApplicazione_update:
    pattern:  /{id}/update
    defaults: { _controller: "FiCoreBundle:menuApplicazione:update" }
    requirements: { _method: post|put }

menuApplicazione_aggiorna:
    pattern:  /aggiorna
    defaults: { _controller: "FiCoreBundle:menuApplicazione:aggiorna" }
    requirements: { _method: post|put }

menuApplicazione_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "FiCoreBundle:menuApplicazione:delete" }
    requirements: { _method: post|delete }

menuApplicazione_deletemultiple:
    pattern:  /delete
    defaults: { _controller: "FiCoreBundle:menuApplicazione:delete" }
    requirements: { _method: post|delete }

menuApplicazione_griglia:
    pattern:  /griglia
    defaults: { _controller: "FiCoreBundle:menuApplicazione:griglia" }
    requirements: { _method: get }
