tabelle:
    pattern:  /
    defaults: { _controller: "FiCoreBundle:tabelle:index" }

tabelle_configura:
    pattern:  /configura/{nometabella}
    defaults: { _controller: "FiCoreBundle:tabelle:configura" }
    requirements: { _method: post|put|get }

tabelle_stampatabella:
    pattern:  /stampatabella/{nometabella}
    defaults: { _controller: "FiCoreBundle:tabelle:stampatabella" }
    requirements: { _method: post|put|get }
    
tabelle_grigliapopup:
    pattern:  /{chiamante}/grigliapopup
    defaults: { _controller: "FiCoreBundle:tabelle:grigliapopup" }
    requirements: { _method: post|put|get }

tabelle_show:
    pattern:  /{id}/show
    defaults: { _controller: "FiCoreBundle:tabelle:show" }

tabelle_new:
    pattern:  /new
    defaults: { _controller: "FiCoreBundle:tabelle:new" }

tabelle_create:
    pattern:  /create
    defaults: { _controller: "FiCoreBundle:tabelle:create" }
    requirements: { _method: post }

tabelle_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "FiCoreBundle:tabelle:edit" }

tabelle_aggiorna:
    pattern:  /aggiorna
    defaults: { _controller: "FiCoreBundle:tabelle:aggiorna" }
    requirements: { _method: post|put }

tabelle_update:
    pattern:  /{id}/update
    defaults: { _controller: "FiCoreBundle:tabelle:update" }
    requirements: { _method: post|put }

tabelle_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "FiCoreBundle:tabelle:delete" }
    requirements: { _method: post|delete }
    
tabelle_deletemultiple:
    pattern:  /delete
    defaults: { _controller: "FiCoreBundle:tabelle:delete" }
    requirements: { _method: post|delete }

tabelle_griglia:
    pattern:  /griglia
    defaults: { _controller: "FiCoreBundle:tabelle:griglia" }
    requirements: { _method: get }
    
