Fi\SpeseBundle\Entity\Categoria:
    type: entity
    table: Categoria
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        descrizione:
            type: string
            length: 255
            nullable: true
    oneToMany:
        tipologias:
            targetEntity: Tipologia
            mappedBy: categoria
            joinColumn:
                name: id
                referencedColumnName: categoria_id