Fi\SpeseBundle\Entity\categoria:
    type: entity
    table: categoria
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        descrizione:
            type: string
            length: 255
            nullable: true
    oneToMany:
        tipologias:
            targetEntity: tipologia
            mappedBy: categoria
            joinColumn:
                name: categoria_id
                referencedColumnName: id
                nullable: false