Fi\SpeseBundle\Entity\Famiglia:
    type: entity
    table: Famiglia
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        descrizione:
            type: string
            length: 255
        dal:
            type: date
        al:
            type: date
            nullable: true
    oneToMany:
        utentes:
            targetEntity: Utente
            mappedBy: famiglia
            joinColumn:
                name: id
                referencedColumnName: famiglia_id