Fi\SpeseBundle\Entity\Movimento:
    type: entity
    table: Movimento
    indexes:
        fk_spesa_tipologia1_idx:
            columns: [ tipologia_id ]
        fk_pagamento_utente1_idx:
            columns: [ utente_id ]
        fk_movimento_tipomovimento1_idx:
            columns: [ tipomovimento_id ]
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        tipologia_id:
            type: integer
        utente_id:
            type: integer
        importo:
            type: float
            precision: 10
            scale: 2
        data:
            type: date
        nota:
            type: string
            length: 4000
            nullable: true
        tipomovimento_id:
            type: integer
    manyToOne:
        tipologia:
            targetEntity: Tipologia
            inversedBy: movimentos
            joinColumn:
                name: tipologia_id
                referencedColumnName: id
        utente:
            targetEntity: Utente
            inversedBy: movimentos
            joinColumn:
                name: utente_id
                referencedColumnName: id
        tipomovimento:
            targetEntity: Tipomovimento
            inversedBy: movimentos
            joinColumn:
                name: tipomovimento_id
                referencedColumnName: id