Fi\SpeseBundle\Entity\Tipologia:
    type: entity
    table: Tipologia
    indexes:
        fk_subcategoria_categoria_idx:
            columns: [ categoria_id ]
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        categoria_id:
            type: integer
        descrizione:
            type: string
            length: 255
    oneToMany:
        movimentos:
            targetEntity: Movimento
            mappedBy: tipologia
            joinColumn:
                name: id
                referencedColumnName: tipologia_id
    manyToOne:
        categoria:
            targetEntity: Categoria
            inversedBy: tipologias
            joinColumn:
                name: categoria_id
                referencedColumnName: id