Fi\SpeseBundle\Entity\Tipomovimento:
    type: entity
    table: Tipomovimento
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        tipo:
            type: string
            length: 45
        abbreviazione:
            type: string
            length: 1
            nullable: true
        segno:
            type: string
            length: 45
    oneToMany:
        movimentos:
            targetEntity: Movimento
            mappedBy: tipomovimento
            joinColumn:
                name: id
                referencedColumnName: tipomovimento_id