Fi\SpeseBundle\Entity\Utente:
    type: entity
    table: Utente
    indexes:
        fk_utente_famiglia1_idx:
            columns: [ famiglia_id ]
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        nome:
            type: string
            length: 255
        cognome:
            type: string
            length: 255
        email:
            type: string
            length: 255
        username:
            type: string
            length: 255
        password:
            type: string
            length: 255
        famiglia_id:
            type: integer
            nullable: true
    oneToMany:
        movimentos:
            targetEntity: Movimento
            mappedBy: utente
            joinColumn:
                name: id
                referencedColumnName: utente_id
    manyToOne:
        famiglia:
            targetEntity: Famiglia
            inversedBy: utentes
            joinColumn:
                name: famiglia_id
                referencedColumnName: id
                nullable: true