
language: php

php:
  - 5.5
  - 5.6

before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - php app/console fifree2:install admin admin admin@admin.it --env=test
  - php app/console gestionespese:installdefaultdata --env=test
  - php app/console server:start --env=test
#  - sh bin/selenium-server-standalone > /dev/null 2>&1 &

script:
  - ant

after_success:
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then php vendor/satooshi/php-coveralls/bin/coveralls -v; fi
  - bin/security-checker -n security:check

notifications:
  email:
  - andrea.manzi@libero.it
