
language: php

php:
  - 5.5
  - 5.6

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - php app/console fifree2:install admin admin admin@admin.it

script:
  - bin/phpunit -c app

after_success:
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then php vendor/bin/vendor/satooshi/php-coveralls/bin/coveralls -v; fi
  - bin/security-checker -n security:check

notifications:
  email:
  - andrea.manzi@libero.it
