language: php

php:
  #- 5.6
  - 7.4
  #- hhvm
  
services:
  - xvfb
  - mysql
  - pgsql
  
# Configure different DB environments
env:
  - DB=mysql
  - DB=postgresql
  - DB=sqlite3

matrix:
    allow_failures:
    #    - php: hhvm
    #    - php: 7.1
    exclude:
    #- php: hhvm
    #  env: DB=pgsql
#sudo: required
#dist: trusty
cache:
  directories:
    - $HOME/.composer/cache

addons:
  firefox: "latest"
  
before_script:
  - sudo apt-get install ant
  - if [[ $TRAVIS_PHP_VERSION != "hhvm" ]] ; then pecl channel-update pecl.php.net; fi;
  - if [[ $TRAVIS_PHP_VERSION == "7.2" ]] ; then echo "yes" | pecl install channel://pecl.php.net/apcu || true; fi
  - if [[ $TRAVIS_PHP_VERSION == "7.2" ]] ; then echo "yes" | pecl install channel://pecl.php.net/apcu_bc || true; fi
  #- if [[ $TRAVIS_PHP_VERSION == "5.6" ]] ; then echo "yes" | pecl install apcu-4.0.11 || true; fi
  - if [[ $TRAVIS_PHP_VERSION == "7.2" ]] ; then sed -i '/extension="apc.so"/d' ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ $TRAVIS_PHP_VERSION == "7.2" ]] ; then sed -i '/extension="apcu.so"/d' ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ $TRAVIS_PHP_VERSION == "7.2" ]] ; then phpenv config-add ./tests/build/ini/apc-7.ini; fi
  #- if [[ $TRAVIS_PHP_VERSION == "5.6" ]] ; then phpenv config-add ./tests/build/ini/apc-5.6.ini; fi
  
  - if [[ "$DB" == "postgresql" ]]; then echo "PROVISIONING WITH PostgreSQL"; fi
  - if [[ "$DB" == "postgresql" ]]; then cp -f ./tests/build/parameters.pgsql.yml $TRAVIS_BUILD_DIR/app/config/parameters.yml; fi
  - if [[ "$DB" == "postgresql" ]]; then psql -c 'create database unittest;' -U postgres; fi
  - if [[ "$DB" == "postgresql" ]]; then psql -d unittest -c '\dt;' -U postgres; fi
  
  - if [[ "$DB" == "mysql" ]]; then echo "PROVISIONING WITH MySQL"; fi
  - if [[ "$DB" == "mysql" ]]; then cp -f ./tests/build/parameters.mysql.yml $TRAVIS_BUILD_DIR/app/config/parameters.yml; fi
  - if [[ "$DB" == "mysql" ]]; then mysql --version; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE unittest;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "GRANT ALL ON unittest.* TO 'travis'@'127.0.0.1';" -uroot; fi
  
  - if [[ "$DB" == "sqlite3" ]]; then echo "PROVISIONING WITH Sqlite3"; fi
  - if [[ "$DB" == "sqlite3" ]]; then cp -f ./tests/build/parameters.sqlite.yml $TRAVIS_BUILD_DIR/app/config/parameters.yml; fi
  - composer install
  - php app/console fifree2:install admin admin admin@admin.it --env=test
  - php app/console gestionespese:installdefaultdata --env=test
  - php app/console server:start --env=test
  - "export DISPLAY=:99.0"
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz && tar -xzf geckodriver-v0.19.1-linux64.tar.gz && sudo mv geckodriver /usr/local/bin
  - sh vendor/bin/selenium-server-standalone > /dev/null 2>&1 &
script:
  - ant

after_success:
  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then php vendor/bin/php-coveralls -v; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then wget https://scrutinizer-ci.com/ocular.phar -t 3; fi;
  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then php ocular.phar code-coverage:upload --format=php-clover build/artifacts/coverage/clover.xml; fi;
  - bin/security-checker -n security:check
  - php app/console server:stop --env=test
  - kill `ps -ef | grep selenium | awk '{ print $2 }'`
  
after_failure:
  - sudo cat app/logs/test.log

notifications:
  email:
  - manzolo@libero.it
