language: php

php:
  - 5.6
  - 7.2
  #- hhvm
  
# Configure different DB environments
env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite3

matrix:
    allow_failures:
    #    - php: hhvm
    #    - php: 7.1
    exclude:
    #- php: hhvm
    #  env: DB=pgsql
#sudo: required
#dist: trusty
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - if [[ "$DB" == "pgsql" ]]; then echo "PROVISIONING WITH PostgreSQL"; fi
  - if [[ "$DB" == "pgsql" ]]; then cp -f ./tests/build/parameters.pgsql.yml $TRAVIS_BUILD_DIR/app/config/parameters.yml; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c 'create database unittest;' -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -d unittest -c '\dt;' -U postgres; fi
  
  - if [[ "$DB" == "mysql" ]]; then echo "PROVISIONING WITH MySQL"; fi
  - if [[ "$DB" == "mysql" ]]; then cp -f ./tests/build/parameters.mysql.yml $TRAVIS_BUILD_DIR/app/config/parameters.yml; fi
  - if [[ "$DB" == "mysql" ]]; then mysql --version; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE unittest;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "GRANT ALL ON unittest.* TO 'travis'@'127.0.0.1';" -uroot; fi
  
  - if [[ "$DB" == "sqlite3" ]]; then echo "PROVISIONING WITH Sqlite3"; fi
  - if [[ "$DB" == "sqlite3" ]]; then cp -f ./tests/build/parameters.sqlite.yml $TRAVIS_BUILD_DIR/app/config/parameters.yml; fi
  - composer install
  - php app/console fifree2:install admin admin admin@admin.it --env=test
  - php app/console gestionespese:installdefaultdata --env=test
  - php app/console server:start --env=test
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - sh vendor/bin/selenium-server-standalone > /dev/null 2>&1 &
script:
  - ant

after_success:
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then php vendor/satooshi/php-coveralls/bin/coveralls -v; fi
  - bin/security-checker -n security:check
  - php app/console server:stop --env=test
  - pkill java

notifications:
  email:
  - andrea.manzi@libero.it
