version: '3'
services:
    app:
        image: manzolo/gestionespesefamiliari_app
        restart: always
        build: 
          context: .
          dockerfile: .docker/onlyapp/php/Dockerfile
        container_name: gestionespesefamiliari_app
        volumes:
            - ./app/cache:/var/www/html/app/cache
            - ./app/logs:/var/www/html/app/logs
            - ./app/config/parameters.yml:/var/www/html/app/config/parameters.yml
        environment:
          MYSQL_HOST: ${MYSQL_HOST}
          MYSQL_PORT: ${MYSQL_PORT}
        ports:
            - ${HTTP_PORT}:80
