imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    #trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    #Questo serve per fare la traduzione della FosUserBundle per le label di username, password, remember_me, ecc..
    translator: { fallback: "%locale%" } 

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        appname: "%appname%"
        database_driver: "%database_driver%"
        database_host: "%database_host%"
        database_name: "%database_name%"
        database_user: "%database_user%"
        solosso: "%solosso%"
    form_themes:
        - FiCoreBundle:Standard:form_div_layout.html.twig

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        path:     "%database_path%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  "UTF8"
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Fi\SpeseBundle:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Fi/SpeseBundle/Entity'
                prefix: 'Fi\SpeseBundle\Entity'
        #query_cache_driver: apcu
        #metadata_cache_driver: apcu
        #result_cache_driver: apcu
        dql:
            string_functions:
                MONTH: DoctrineExtensions\Query\Mysql\Month
                YEAR: DoctrineExtensions\Query\Mysql\Year
            datetime_functions:
                 MONTH:  DoctrineExtensions\Query\Sqlite\Month
                 YEAR: DoctrineExtensions\Query\Sqlite\Year

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Fi\CoreBundle\Entity\Operatori
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

parameters:
    locale: it
    appname: gestionespesefamiliari
    appid_applicativo: 999
    user4test: admin
    solosso: false
    # 1 se l'accesso è solo sso
