fi_spese:
    resource: "@FiSpeseBundle/Resources/config/routing.yml"
    prefix:   /

fi_pannello_amministrazione:
    resource: "@FiPannelloAmministrazioneBundle/Resources/config/routing.yml"
    prefix:   /

autenticazione:
    resource: "@AutenticazioneBundle/Resources/config/routing.yml"
    prefix:   /

fi_core:
    resource: "@FiCoreBundle/Resources/config/routing.yml"
    prefix:   /

#HOMEPAGE ROUTE
homepage:
    prefix:   /
    path:      /
    defaults: { _controller: FiSpeseBundle:movimento:index }
    requirements:
      _method:  GET

