version: '3'
services:
    mysql:
        image: mysql
        restart: always
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: gestionespesefamiliari_mysql
        volumes:
            - ./data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    app:
        image: manzolo/gestionespesefamiliari_app
        restart: always
        build: 
          context: .
          dockerfile: .docker/full/php/Dockerfile
        container_name: gestionespesefamiliari_app
        volumes:
            - ./app/cache:/app/app/cache
            - ./app/logs:/app/app/logs
            - ./app/config/parameters.yml:/app/app/config/parameters.yml
        ports:
            - ${APACHE_PORT}:8030
        depends_on:
          - mysql

    phpmyadmin:
        restart: always
        image: phpmyadmin/phpmyadmin
        container_name: gestionespesefamiliari_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
          PHPMYADMIN_PORT: ${PHPMYADMIN_PORT}
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - ${PHPMYADMIN_PORT}:80
        depends_on:
          - mysql
