android_login:
    path:  /login
    defaults: { _controller: "FiSpeseBundle:android:login" }
    requirements: { methods: post }
    
android_gettipologie:
    path:  /gettipologie
    defaults: { _controller: "FiSpeseBundle:android:getTipologie" }

android_gettipimovimento:
    path:  /gettipimovimento
    defaults: { _controller: "FiSpeseBundle:android:getTipimovimento" }

android_registraspesa:
    path:  /registraspesa
    defaults: { _controller: "FiSpeseBundle:android:registraSpesa" }
    requirements: { methods: post }
    
android_appcurrentversion:
    path:  /appCurrentVersion
    defaults: { _controller: "FiSpeseBundle:android:appCurrentVersion" }

android_getappapk:
    path:  /getAppApk
    defaults: { _controller: "FiSpeseBundle:android:getAppApk" }

android_getultimimovimenti:
    path:  /getultimimovimenti
    defaults: { _controller: "FiSpeseBundle:android:getUltimiMovimenti" }
    
android_getcategorie:
    path:  /getcategorie
    defaults: { _controller: "FiSpeseBundle:android:getCategorie" }

android_gettipimovimento:
    path:  /gettipimovimento
    defaults: { _controller: "FiSpeseBundle:android:getTipimovimento" }
    
android_deletemovimenti:
    path:  /deletemovimenti
    defaults: { _controller: "FiSpeseBundle:android:deleteMovimenti" }
    requirements: { methods: post }
    