android_login:
    pattern:  /login
    defaults: { _controller: "FiSpeseBundle:android:login" }
    requirements: { _method: post }
    
android_gettipologie:
    pattern:  /gettipologie
    defaults: { _controller: "FiSpeseBundle:android:getTipologie" }

android_gettipimovimento:
    pattern:  /gettipimovimento
    defaults: { _controller: "FiSpeseBundle:android:getTipimovimento" }

android_registraspesa:
    pattern:  /registraspesa
    defaults: { _controller: "FiSpeseBundle:android:registraSpesa" }
    requirements: { _method: post }
    
android_appcurrentversion:
    pattern:  /appCurrentVersion
    defaults: { _controller: "FiSpeseBundle:android:appCurrentVersion" }

android_getappapk:
    pattern:  /getAppApk
    defaults: { _controller: "FiSpeseBundle:android:getAppApk" }

android_getultimimovimenti:
    pattern:  /getultimimovimenti
    defaults: { _controller: "FiSpeseBundle:android:getUltimiMovimenti" }
    
android_getcategorie:
    pattern:  /getcategorie
    defaults: { _controller: "FiSpeseBundle:android:getCategorie" }

android_gettipimovimento:
    pattern:  /gettipimovimento
    defaults: { _controller: "FiSpeseBundle:android:getTipimovimento" }
    
android_deletemovimenti:
    pattern:  /deletemovimenti
    defaults: { _controller: "FiSpeseBundle:android:deleteMovimenti" }
    requirements: { _method: post }
    