android_login:
    pattern:  /login
    defaults: { _controller: "FiSpeseBundle:android:login" }
    requirements: { _method: post }
    
android_gettipologie:
    pattern:  /gettipologie
    defaults: { _controller: "FiSpeseBundle:android:getTipologie" }

android_gettipimovimento:
    pattern:  /gettipimovimento
    defaults: { _controller: "FiSpeseBundle:android:getTipimovimento" }

android_registraspesa:
    pattern:  /registraspesa
    defaults: { _controller: "FiSpeseBundle:android:registraSpesa" }
    requirements: { _method: post }
    
android_appcurrentversion:
    pattern:  /appCurrentVersion
    defaults: { _controller: "FiSpeseBundle:android:appCurrentVersion" }

android_getappapk:
    pattern:  /getAppApk
    defaults: { _controller: "FiSpeseBundle:android:getAppApk" }
