android_login:
    pattern:  /login
    defaults: { _controller: "FiSpeseBundle:android:login" }
    
android_gettipologie:
    pattern:  /gettipologie
    defaults: { _controller: "FiSpeseBundle:android:getTipologie" }

android_gettipimovimento:
    pattern:  /gettipimovimento
    defaults: { _controller: "FiSpeseBundle:android:getTipimovimento" }

android_registraspesa:
    pattern:  /registraspesa
    defaults: { _controller: "FiSpeseBundle:android:registraSpesa" }
    
