categoria_container:
    path:  /
    defaults: { _controller: "FiSpeseBundle:categoria:index" }

categoria_new:
    path:  /new
    defaults: { _controller: "FiSpeseBundle:categoria:new" }

categoria_create:
    path:  /create
    defaults: { _controller: "FiSpeseBundle:categoria:create" }
    requirements: { methods: post }

categoria_edit:
    path:  /{id}/edit
    defaults: { _controller: "FiSpeseBundle:categoria:edit" }

categoria_update:
    path:  /{id}/update
    defaults: { _controller: "FiSpeseBundle:categoria:update" }
    requirements: { methods: post|put }

categoria_aggiorna:
    path:  /aggiorna
    defaults: { _controller: "FiSpeseBundle:categoria:aggiorna" }
    requirements: { methods: post|put }

categoria_delete:
    path:  /{id}/delete
    defaults: { _controller: "FiSpeseBundle:categoria:delete" }
    requirements: { methods: post|delete }

categoria_deletemultiple:
    path:  /delete
    defaults: { _controller: "FiSpeseBundle:categoria:delete" }
    requirements: { methods: post|delete }

categoria_griglia:
    path:  /griglia
    defaults: { _controller: "FiSpeseBundle:categoria:griglia" }
    requirements: { methods: get|post }