movimento_container:
    pattern:  /
    defaults: { _controller: "FiSpeseBundle:movimento:index" }

movimento_new:
    pattern:  /new
    defaults: { _controller: "FiSpeseBundle:movimento:new" }

movimento_create:
    pattern:  /create
    defaults: { _controller: "FiSpeseBundle:movimento:create" }
    requirements: { _method: post }

movimento_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "FiSpeseBundle:movimento:edit" }

movimento_update:
    pattern:  /{id}/update
    defaults: { _controller: "FiSpeseBundle:movimento:update" }
    requirements: { _method: post|put }

movimento_aggiorna:
    pattern:  /aggiorna
    defaults: { _controller: "FiSpeseBundle:movimento:aggiorna" }
    requirements: { _method: post|put }

movimento_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "FiSpeseBundle:movimento:delete" }
    requirements: { _method: post|delete }

movimento_deletemultiple:
    pattern:  /delete
    defaults: { _controller: "FiSpeseBundle:movimento:delete" }
    requirements: { _method: post|delete }

movimento_griglia:
    pattern:  /griglia
    defaults: { _controller: "FiSpeseBundle:movimento:griglia" }
    requirements: { _method: get }