movimento_container:
    path:  /
    defaults: { _controller: "FiSpeseBundle:movimento:index" }

movimento_new:
    path:  /new
    defaults: { _controller: "FiSpeseBundle:movimento:new" }

movimento_create:
    path:  /create
    defaults: { _controller: "FiSpeseBundle:movimento:create" }
    requirements: { methods: post }

movimento_edit:
    path:  /{id}/edit
    defaults: { _controller: "FiSpeseBundle:movimento:edit" }

movimento_update:
    path:  /{id}/update
    defaults: { _controller: "FiSpeseBundle:movimento:update" }
    requirements: { methods: post|put }

movimento_aggiorna:
    path:  /aggiorna
    defaults: { _controller: "FiSpeseBundle:movimento:aggiorna" }
    requirements: { methods: post|put }

movimento_delete:
    path:  /{id}/delete
    defaults: { _controller: "FiSpeseBundle:movimento:delete" }
    requirements: { methods: post|delete }

movimento_deletemultiple:
    path:  /delete
    defaults: { _controller: "FiSpeseBundle:movimento:delete" }
    requirements: { methods: post|delete }

movimento_griglia:
    path:  /griglia
    defaults: { _controller: "FiSpeseBundle:movimento:griglia" }
    requirements: { methods: get|post }