reports_container:
    pattern:  /
    defaults: { _controller: "FiSpeseBundle:reports:index" }

utente_new:
    pattern:  /new
    defaults: { _controller: "FiSpeseBundle:utente:new" }

utente_create:
    pattern:  /create
    defaults: { _controller: "FiSpeseBundle:utente:create" }
    requirements: { _method: post }

utente_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "FiSpeseBundle:utente:edit" }

utente_update:
    pattern:  /{id}/update
    defaults: { _controller: "FiSpeseBundle:utente:update" }
    requirements: { _method: post|put }

utente_aggiorna:
    pattern:  /aggiorna
    defaults: { _controller: "FiSpeseBundle:utente:aggiorna" }
    requirements: { _method: post|put }

utente_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "FiSpeseBundle:utente:delete" }
    requirements: { _method: post|delete }

utente_deletemultiple:
    pattern:  /delete
    defaults: { _controller: "FiSpeseBundle:utente:delete" }
    requirements: { _method: post|delete }

utente_griglia:
    pattern:  /griglia
    defaults: { _controller: "FiSpeseBundle:utente:griglia" }
    requirements: { _method: get }