tipomovimento_container:
    pattern:  /
    defaults: { _controller: "FiSpeseBundle:tipomovimento:index" }

tipomovimento_new:
    pattern:  /new
    defaults: { _controller: "FiSpeseBundle:tipomovimento:new" }

tipomovimento_create:
    pattern:  /create
    defaults: { _controller: "FiSpeseBundle:tipomovimento:create" }
    requirements: { _method: post }

tipomovimento_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "FiSpeseBundle:tipomovimento:edit" }

tipomovimento_update:
    pattern:  /{id}/update
    defaults: { _controller: "FiSpeseBundle:tipomovimento:update" }
    requirements: { _method: post|put }

tipomovimento_aggiorna:
    pattern:  /aggiorna
    defaults: { _controller: "FiSpeseBundle:tipomovimento:aggiorna" }
    requirements: { _method: post|put }

tipomovimento_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "FiSpeseBundle:tipomovimento:delete" }
    requirements: { _method: post|delete }

tipomovimento_deletemultiple:
    pattern:  /delete
    defaults: { _controller: "FiSpeseBundle:tipomovimento:delete" }
    requirements: { _method: post|delete }

tipomovimento_griglia:
    pattern:  /griglia
    defaults: { _controller: "FiSpeseBundle:tipomovimento:griglia" }
    requirements: { _method: get|post }