Tipologia_container:
    path:  /
    defaults: { _controller: "FiSpeseBundle:Tipologia:index" }

Tipologia_new:
    path:  /new
    defaults: { _controller: "FiSpeseBundle:Tipologia:new" }

Tipologia_create:
    path:  /create
    defaults: { _controller: "FiSpeseBundle:Tipologia:create" }
    requirements: { methods: post }

Tipologia_edit:
    path:  /{id}/edit
    defaults: { _controller: "FiSpeseBundle:Tipologia:edit" }

Tipologia_update:
    path:  /{id}/update
    defaults: { _controller: "FiSpeseBundle:Tipologia:update" }
    requirements: { methods: post|put }

Tipologia_aggiorna:
    path:  /aggiorna
    defaults: { _controller: "FiSpeseBundle:Tipologia:aggiorna" }
    requirements: { methods: post|put }

Tipologia_delete:
    path:  /{id}/delete
    defaults: { _controller: "FiSpeseBundle:Tipologia:delete" }
    requirements: { methods: post|delete }

Tipologia_deletemultiple:
    path:  /delete
    defaults: { _controller: "FiSpeseBundle:Tipologia:delete" }
    requirements: { methods: post|delete }

Tipologia_griglia:
    path:  /griglia
    defaults: { _controller: "FiSpeseBundle:Tipologia:griglia" }
    requirements: { methods: get|post }