Utente_container:
    path:  /
    defaults: { _controller: "FiSpeseBundle:Utente:index" }

Utente_new:
    path:  /new
    defaults: { _controller: "FiSpeseBundle:Utente:new" }

Utente_create:
    path:  /create
    defaults: { _controller: "FiSpeseBundle:Utente:create" }
    requirements: { methods: post }

Utente_edit:
    path:  /{id}/edit
    defaults: { _controller: "FiSpeseBundle:Utente:edit" }

Utente_update:
    path:  /{id}/update
    defaults: { _controller: "FiSpeseBundle:Utente:update" }
    requirements: { methods: post|put }

Utente_aggiorna:
    path:  /aggiorna
    defaults: { _controller: "FiSpeseBundle:Utente:aggiorna" }
    requirements: { methods: post|put }

Utente_delete:
    path:  /{id}/delete
    defaults: { _controller: "FiSpeseBundle:Utente:delete" }
    requirements: { methods: post|delete }

Utente_deletemultiple:
    path:  /delete
    defaults: { _controller: "FiSpeseBundle:Utente:delete" }
    requirements: { methods: post|delete }

Utente_griglia:
    path:  /griglia
    defaults: { _controller: "FiSpeseBundle:Utente:griglia" }
    requirements: { methods: get|post }